# Site settings
title: gmacario.github.io
#email: gmacario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gianpaolo Macario public rants 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gmacario.github.io" # the base hostname & protocol for your site
twitter_username: gpmacario
github_username:  gmacario

# Build settings
markdown: kramdown
