title: "gmacario.github.io"
description: "Gianpaolo Macario's public rants"
social: [{
    icon: "github.svg",
    name: "gmacario",
    link: "https://github.com/gmacario"
  },
  { icon: "twitter.svg", 
    name: "gpmacario",
    link: "https://www.twitter.com/gpmacario"
  }]