title: "gmacario.github.io"
description: "Gianpaolo Macario's public rants"
social: {
  github: {
    name: "gmacario",
    link: "https://github.com/gmacario"
    },
  twitter: {
    name: "gpmacario",
    link: "https://www.twitter.com/gpmacario"
  }
}